### ISSUE TITLE
Feature Request - bind chart version with application image version

### ISSUE THREAD

**Issue by wojtek-szymik** [r-d-kmd/gradle-helm-chart-publisher#2]
Currently application image and helm chart are released together with the same versioning schema but there is no easy way to bind exact application image version to the same chart version. Usually there is a pointer to HEAD or latest version of app image in values.yaml file but there should be a way to point to the same version as chart.

```yaml
image:
  repository: some-docker-repo/image-of-app
  tag: the-same-version-as-chart
  pullPolicy: Always
```

**Comment by jpt-avaleo** [comment]
I don't think that this is in scope of this plugin. What this plugin does it packages without modifying existing helm chart and pushes it to a git repository.

What I propose is to use a tool to modify a values.yaml file before publishing it to a helm repository? I believe that [yq](https://github.com/mikefarah/yq) would be perfect for that, with that you can do something like this:

`yq w -i values.yaml 'image.tag' your-new-version-here`

to change image.tag version in `values.yaml` file before publishing the chart to repository. This seems like a reasonable solution to your issue.

**Comment by jozala** [comment]
In Helm v3 client there is an argument `--app-version` for `helm package` command which allows to set version of the application during packaging Helm chart. 
This version is then set as a value for "appVersion" in Chart.yaml file and can be used in deployment with `.Chart.AppVersion` for image tag like this:

```yaml
    spec:
      containers:
        - image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
```

This is how it is used in the default generated Helm v3 chart.

So maybe this plugin could take application version as parameter and pass it to `helm template` command.
